### ISSUE TITLE
Watermark happens on a layer level, not page level

### ISSUE THREAD

**Issue by javiersc1** [JeffFessler/WatermarkSolutions#1]
Making a comment here that this approach is easily bypassed by using something like Inkscape since the watermark is a separate layer that can be removed. The correct way to deal with this would be to merge the watermark to the page itself maybe?

Writing this here so I don't forget to bring it up later.

**Comment by JeffFessler** [comment]
btw, the code shown here is not what is being used by dco in eecs.
they have custom python scripts

**Comment by javiersc1** [comment]
Ah ok, I assumed this was the same. I doubt they use github to manage that stuff so I can't open an issue. I'm not optimistic about this getting fixed even if I notify them but might be worth doing so.
