### ISSUE TITLE
Watermark not shown on specific documents due to layer organization

### ISSUE THREAD

**Issue by javiersc1** [JeffFessler/WatermarkSolutions#2]
See f22-e2.pdf on https://w2p.eecs.umich.edu/fessler1

Watermark not shown, possibly need to make the watermark the top layer in the document so that it always shows up on top?

Additionally for some PDF elements, like a giant code block, the watermark renders behind it.

Writing it here before I forget.

**Comment by JeffFessler** [comment]
I see the watermark on most pages of that doc, in acrobat reader and in preview on a mac.
It doesn't show fully on some pages, but that's ok i think.
Are you saying it doesn't show at all?  What pdf viewer on what OS?

**Comment by javiersc1** [comment]
The standard PDF viewer that ships with Firefox (built in) running on Fedora 39. Most documents have the watermark but this one does not have one for me. f22-e1 does have the watermark so it's not an issue from my end, no idea why this document doesn't have it but I've seen stuff like this happen before under Laura's class. Some pages not having it etc..

This is an issue for DCO so I'll close this one.
